### ISSUE TITLE
Data file format

### ISSUE THREAD

**Issue by blackdjinn** [CSULA-Qdots/filter#14]
One of the reasons we were using the file format (for processed output files) that we are is because the curve fitting program (that we no longer use IIRC) expected data in just a certain way and was problematic to extend.

The filter program works on a load/transform/write model and can spit data out however we want.

Thoughts?

**Comment by jbouzanquet** [comment]
The old program (that I wrote) was hardcoded with the format, but I'm not actually sure how ipf.m decides what to operate on. I could read through it now, I'd imagine it operates on some generalization of a csv table, probably assuming row-to-row symmetry. So we can't deviate from that while using ipf.m . We may need to extend filter (or add an additional processing step) to handle corrections for the laser input, if we decide it's actually a factor. Which isn't totally clear.

**Comment by jbouzanquet** [comment]
I realize now that Matlab is loading and serializing the files, and we load the already constructed matrix into ipf. Matlab loads our current data format into a string, a string matrix, and the numerical (floating point?)  "data" matrix. So textual header amounts and contents can change freely. There is some limitation on the kind of numerical data in the file though. From the comments in the top of the program:

> % Keyboard-operated Interactive Peak Fitter for data in separate x,y
> % vectors, or in a single y vector, or in a 2xn or nx2 data matrix with
> % x values in row/column 1 and y values in row/column 2 (e.g. [x y]).

So we can change the output file format to something more convenient, perhaps allowing a little more copy-paste in making the spreadsheets. Might I suggest

```
"Title from first line now in quotes to avoid splitting into multiple cells","","",""
"Wavelength/Energy","Spectral Intensity","Laser Intensity","Temperature"
```

There are several points to make about this idea
- This works equally well as csv (or any other delimiter) or fixed-width, but delimited files should be marginally smaller.
- The empty strings are simply for symmetry, Matlab automatically places headers in a different variable and LO Calc and MS Excel should import a blank cell either way. 
- The temperature column would preferably be the actual Kelvin temperature, which we could find from the voltages in the original file and the chart in the lab somewhere. 
  - When I get ahold of it I'll try to fit the data table with a line or perhaps multiple line formulas. Aaron, please do that if you have the chance. The chart should be in the milk crate with all our equipment specs. 
- It would be possible to put both wavelength and energy columns in the same file, but ipf ignores columns after the second and Calc and Excel will automatically graph with the independent variable as the leftmost column, so we gain little utility from doing so.
  - The same applies to whether there should be a laser-corrected spectral intensity column, but it isn't a clear no to me. Both uncorrected and corrected are dependent variables, and graphing both may be useful in determining if they are visually distinct enough to warrant further testing. Doing so would still have the problem that ipf won't fit it without moving the column and saving the csv file again.

**Comment by jbouzanquet** [comment]
Here's a note to myself that is relevant to the data format.

ipf turns out to have a, instantiation form that allows selecting the dependent variables manually. The usual double-click loading we use on a data file generates a 3 columned N rowed matrix variable. If the format had multiple independent and dependent variables, they could be selected with that instantiation. Assuming two variables of each kind, in the file ordered ind,ind,dep,dep, dependent 1 vs independent 2 would be 

`ipf(data(:,1),data(:,4))`

Independent 2 vs dependent 1
`ipf(data(:,2),data(:,3))`

Same as above, with the fitting window centered roughly appropriately for fitting an eV curve
`ipf(data(:,2),data(:,3),1.4,0.4)`

Aaron's lazy.m program has some scripted version of the data load. Maybe a variation of the code in baselineCorrector could load a data file and ipf the correct set of variables and center the window to somewhat reduce time to analyse. The difference would be small for a single file, but could be significant for doing many of them. Using a shell glob to input the filenames is much less error-prone than attempting to doubleclick the right entry in a list of dozens though, so it could reduce error while having little effect on speed. I'll try to write this today.

There could be several copies of the script, or a command line switch behavior, to choose between eV, wavelength, spectrometer output with permutations of correction types, all loaded out of one out file, eliminating the need for duplicate output files concerning the same sample run. The original files could not be replaced however, because rejecting any data would reduce the number of rows in the matrix. Testing finds that matlab only allows regular matrices, and attempting to unify raw and analysed data would create the form 
`[350-line col][350-line col][350-line col][300-line col][300-line col][300-line col]`

Which in Matlab results in a single 350x6 matrix where 301,4 --> 350,6 are 0.

**Comment by blackdjinn** [comment]
OK. Now that I have the new options logic worked out (needed for the laser-detect and however we want to be able to specify output) the effects of it can start propagating through the rest of the code. NOTE: the .filterrc file format has changed, and might change again before I'm done. That said, should I push my changes into mainline? You can find them in the rd.features branch on the server.

**Comment by jbouzanquet** [comment]
Sure, why not push? I haven't symlinked the executables we use to the development copies. So the current ones stay until we have something stable.

**Comment by blackdjinn** [comment]
They're pushed up, just not merged... I have a separate branch for the changes I'm making.

**Comment by jbouzanquet** [comment]
I'm not doing any work on that program but the branch I already tried and failed to modify. Neither is Aaron, so merge freely.
