### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by blackdjinn** [CSULA-Qdots/filter#16]
Since this code is ending up in your thesis, I'm guessing you'd like better comments in filter. Tell me what you're after and I can put them in.

**Comment by jbouzanquet** [comment]
It's in there, but that portion is being explained by a few sentences in the text. I just thought it needs to be in there since I'm writing on the analysis steps. I added high level comments to the shell files explaining the general operation, both for the thesis and for anyone trying to figure out the previously terse scripts. So all it really needs is lines explaining the logic, I don't expect the readers to follow the program code.

**Comment by blackdjinn** [comment]
OK. Close this if you're good with what I have.

**Comment by jbouzanquet** [comment]
Meh. I have a description written, it isn't critical if non-coders can't follow this. I might add some comments later on if I feel like it.
